### ISSUE TITLE
Hardware plans/notes

### ISSUE THREAD

**Issue by 1-max-1** [1-max-1/heli-avionics#1]
### MCU
Looking at atmega4809. I have experience with this already, programming it is fairly easy. It has SPI, I2C and PWM so should be good.
Flash size should be enough. Bootloaders are simple.

### RF
Will be wired to nrf24 chip. Schematic for this can be found in datasheets and there are plenty of examples online, including the PCB antenna and impedance matching network. Maybe use 4 layer PCB and keep all RF circuitry on separate layer. nrf24 needs a 16MHz crystal, JLC only has the [X322516MLB4SI](https://jlcpcb.com/partdetail/Yxc_CrystalOscillators-X322516MLB4SI/C13738) on basic parts but might need to change later.

**Antenna**
Will use a wire antenna, as it seems to have the best range. Definitely don't have room for pcb antenna, and chip antennas are weird. Will use 20 gauge wire, uninsulated, solid core wire would stand up easier but tron lab only has stranded.

### Motor drivers
Brushed, DC, x3. Drive through PWM. Could use motor driver chip, or mosfets directly.
Needs plenty of decoupling on MCU to avoid reset from current spike.
Use `DRV8212`, non-P version as it supports half bridge mode.

**Capacitors**
For example,
big one: [RL1A332MG250A00CE0](https://www.lcsc.com/product-detail/Aluminum-Electrolytic-Capacitors-Leaded_Changzhou-Huawei-Elec-RL1A332MG250A00CE0_C240437.html)

smaller: [SPT1AM102E14ORVZC](https://www.lcsc.com/product-detail/Aluminum-Electrolytic-Capacitors-Leaded_Yunxing-SPT1AM102E14ORVZC_C3024245.html)

but could just get from ece store. **Edit:** ECE store ones are wayy too big.

### Altitude sensor
Some kind of pressure sensor, preferably over SPI. Looking like BMP388 is a good choice, fairly accurate, well documented and needs minimal supporting circuitry. Edit: BMP390 is the next iteration.

### Battery
Seems like the original battery is just a single cell, but quite large. mcu and nrf24 runs on 3.3v max so need LDO.
No onboard battery charging system due to complexity and fire hazard. Power switch will just link the battery to charging port, which can be used with off the shelf lipo charger.
Also need battery monitoring system to avoid using the cells when below safe threshold: Use voltage divider to analog pin. Voltage divider can be disabled with mosfet (when not reading battery level) to prevent current usage. Need a mosfet with low drive voltage. [AO3400A](https://jlcpcb.com/partdetail/Alpha_OmegaSemicon-AO3400A/C20917) is ideal as it is in the basic parts list.

[This](https://www.kiwiquads.co.nz/product/gnb-battery-3-8v-60c-850mah-1s-ph2/) battery seems good, 850mAh should be about 5 minutes of flight time which is decent. Uses `PH2` connector, can be found 

### Voltage regulator
Use battery directly to power motors, everything else runs off 3.0V LDO. Will need something with a very low dropout (< 50mV) to use the full charge of the lipo.
Candidates in stock at jlc and pcbx:
- [HE2021A30HPR](https://www.pcbx.com/component-detail/HEERMICR-HE2021A30HPR-500264740)
- [NCP551SN30T1G](https://www.pcbx.com/component-detail/On%20Semiconductor-NCP551SN30T1G-500265789)

Probably will go with `HE2021A30HPR` as it seems to have better parameters, higher output current and cheaper price.

Update:
Seems like we shouldn't go below 3.2v with lipo, so we don't actually need too low dropout on the LDO. 100mV-150mV will do.
The `TPS7A2030` looks like a good candidate, it is an improvement on the `LP5907MFX-3.0`.

**Comment by 1-max-1** [comment]
**TODO:**

- [x] 2x LED's on GPIO pins, not power (always on) because waste of current. Maybe one on the bootloader pin.
- [x] Component values should be in common E-series
- [x] Testpoints
- [x] Check pin order on connectors
- [x] Check footprints and pin order on all components
- [x] Spare exposed GPIO and I2C
- [x] UART programming
- [x] Exposed pad/hole for additional decoupling to be added if needed. Edit: there is no room, so just solder onto the existing pins or maybe even the testpoints if we have to.
- [x] Antenna
- [x] Sort out the crystal (and crystal footprint)
- [x] Check heat sink sizes
- [x] Confirm battery connector footprint once battery is chosen
- [x] Check SMD resistor power dissipation limits
- [x] Check electrolytic capacitor sizes and footprints
- [x] Check via clearance annulus, maybe remove inner copper anulus too
- [x] missing 3d models
- [x] Check thermal relief connections, can these support high current? Add vias to help with conduction?
- [x] Battery charging current track
- [x] Fix ERC warning on pin 5 of pressure sensor
- [x] NPTH on mechanical layer.
- [x] No soldermask on back of 2 motor driver thermal vias.
- [x] [Minimum spacing](https://jlcpcb.com/help/article/SMD-Components-Minimum-Spacing) between components.
- [x] Change LED resistors to `0805` package.

**Comment by 1-max-1** [comment]
### RF components
**1.5pF cap**
LCSC: [C3869699](https://www.lcsc.com/product-detail/Multilayer-Ceramic-Capacitors-MLCC-SMD-SMT_Murata-Electronics-GQM1875C2E1R5BB12D_C3869699.html)
digikey: [1292-HH18N1R5B500CTTR-ND](https://www.digikey.com/en/products/detail/walsin-technology-corporation/HH18N1R5B500CT/15980295)

**1 pF cap**
LCSC: [C2178951](https://www.lcsc.com/product-detail/Multilayer-Ceramic-Capacitors-MLCC-SMD-SMT_Murata-Electronics-GQM1875C2E1R0BB12D_C2178951.html)
digikey: [1292-HH18N1R0B500CTTR-ND](https://www.digikey.com/en/products/detail/walsin-technology-corporation/HH18N1R0B500CT/15979307)

**8.2nF inductor**
LCSC: [C90204](https://www.lcsc.com/product-detail/Inductors-SMD_FH-Guangdong-Fenghua-Advanced-Tech-VHF160808H8N2JT_C90204.html)
digikey: [BSCQ000603038N2H00](https://www.digikey.com/en/products/detail/pulse-electronics/BSCQ000603038N2H00/16514793)

**3.9 nF inductor**
LCSC: [C90202](https://www.lcsc.com/product-detail/Inductors-SMD_FH-Guangdong-Fenghua-Advanced-Tech-VHF160808H3N9ST_C90202.html)
digikey: [BSCQ000603033N9B00](https://www.digikey.com/en/products/detail/pulse-electronics/BSCQ000603033N9B00/10508643)

**2.7 nF inductor**
LCSC: [C83929](https://www.lcsc.com/product-detail/Inductors-SMD_FH-Guangdong-Fenghua-Advanced-Tech-VHF160808H2N7ST_C83929.html)
digikey: [BSCQ000603032N7B00](https://www.digikey.com/en/products/detail/pulse-electronics/BSCQ000603032N7B00/10508492)
